version: "3.3"

services:
  
  websocket-microservice:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: websocket-microservice
    ports:
      - "5099:5099"
    networks:
      my-custom-network:
  
  network-visualizer:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: network-visualizer
    ports:
      - "4204:4204"
    environment:
      - REACT_APP_BASE_PATH=/
      - REACT_APP_STATIC_CONTENT_PATH=http://localhost:4204
    networks:
      my-custom-network:

networks:
  my-custom-network:
