version: "3.3"

services:
  
  websocket-microservice:
    image: ncats/aicp-websocket-microservice:latest
    container_name: websocket-microservice
    ports:
      - "${port_websocket_microservice}:${port_websocket_microservice}"
    volumes:
      - $PWD/common:/common
    env_file:
      - ./.env
    networks:
      my-custom-network:
        aliases:
         - ${network_alias_websocket_microservice}
  
  network-visualizer:
    image: ncats/aicp-network-visualizer:latest
    container_name: network-visualizer
    ports:
      - "${port_force_directed_graph}:3000"
    environment:
      - REACT_APP_WEBSOCKET_URL=http://localhost:${port_websocket_microservice}/ws
      - REACT_APP_IN_STANDALONE_MODE=true
    networks:
      my-custom-network:
        aliases:
          - ${network_alias_force_directed_graph}

networks:
  my-custom-network: