version: "3.8"
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "4204:4204"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:4204/}
      - API_URL=${API_URL:-http://0.0.0.0:5099}
